version: "3"
services:
  composedapp:
    image: composed-app:latest
    ports:
      - 8080:8080
      - 3000:3000
    depends_on: 
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
volumes:
  todo-mysql-data: